Add test_email_validation.py
kpi-web-guild/email-validation-util pull request #9
Opened 2016-12-19 21:25 UTC by m04116

2016-12-19 22:05 UTC, webknjaz requested changes
.0. RTFM
.1. Read the task carefully in loop until understood :)

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +
dummy line

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +import re
not needed here

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +def validate_email(a):
1) not here
2) argument name sucks
3) should be returning value
4) should have a comprehensive docstring

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +    pattern = r'^([a-z]+|[0-9])*@[a-z]+_?[a-z]+\.com$'
not needed

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +    if re.match(pattern, a):
not needed

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +        print('True')
not needed

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +    else:
not needed

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +        print('False')
not needed

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +e_mail = 'vasya@gde-to.ru'
WTF?

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +
where's docstring?

2016-12-19 22:05 UTC, webknjaz commented on test_email_validation.py
> +        self.assertTrue(e_mail, validate_email())
Invalid check: see the documentation for the input arguments.

2016-12-19 22:07 UTC, webknjaz commented
Make the PR title correspond its contents and add some short description on what you did here

2016-12-20 19:36 UTC, webknjaz requested changes

2016-12-20 19:36 UTC, webknjaz commented on .pre-commit-config.yaml
> + -   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
Indentation style here does not match section above

2016-12-20 19:36 UTC, webknjaz commented on email_validation.py
> +import re
YAGNI

2016-12-20 19:36 UTC, webknjaz commented on email_validation.py
> +    pattern = r'^([a-z]+|[0-9])*@[a-z]+_?[a-z]+\.com$'
See the task

2016-12-20 19:36 UTC, webknjaz commented on email_validation.py
> +a = 'vasya@gde-to.ru'
rm

2016-12-20 19:36 UTC, webknjaz commented on test_email_validation.py
> +e_mail = 'vasya@gde-to.ru'
rm

2016-12-20 19:36 UTC, webknjaz commented on test_email_validation.py
> +        self.assertTrue(e_mail, validate_email())
`validate_email` does not exist in this scope

2016-12-21 14:17 UTC, webknjaz requested changes

2016-12-21 14:17 UTC, webknjaz commented on .gitignore
> +.virtualenvs/
normally you don't need to `.gitignore` any of these

2016-12-21 14:17 UTC, webknjaz commented on email_validation.py
> +def validate_email(email):
correct

2016-12-21 14:17 UTC, webknjaz commented on test_email_validation.py
> +import email_validation
usually stdlib modules are imported first and only after them you import your own project modules

2016-12-21 14:17 UTC, webknjaz commented on test_email_validation.py
> +        self.assertTrue(email, validate_email())
1) This is invalid: `assertTrue()` accepts only one argument for test.
2) `email` variable doesn't exist in this scope

2016-12-24 21:00 UTC, webknjaz requested changes

2016-12-24 21:00 UTC, webknjaz commented on test_email_validation.py
> +        self.assertTrue('123@123.com', email_validation.validate_email())
Read the doc

2016-12-24 21:00 UTC, webknjaz commented on test_email_validation.py
> +    """unit test for EmailValidation"""
Docstrings are usually sentences (i.e. start with uppercase letter and end with a period)

2016-12-24 21:00 UTC, webknjaz commented on email_validation.py
> +"""validate email module."""
Uppercase `V`

2016-12-24 21:41 UTC, webknjaz commented on test_email_validation.py
> +        self.assertTrue('123@123.com', email_validation.validate_email())
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue

2016-12-25 11:09 UTC, webknjaz requested changes
Change travis script section to
```
script:
- nosetests
- pre-commit run --all-files
```

2016-12-25 11:30 UTC, webknjaz requested changes

2016-12-25 11:30 UTC, webknjaz commented on test_email_validation.py
> +import email_validation
Could you please use `import from` syntax instead?

2016-12-25 11:34 UTC, webknjaz commented on test_email_validation.py
> +import unittest
You may fulfill my previous requirement enabling one of `reorder-python-imports` or `python-import-sorter` in pre-commit's config.

2016-12-25 11:39 UTC, webknjaz commented on .travis.yml
> +- nosetests
Add `-s -v` arguments to `nosetests`

2016-12-25 12:53 UTC, m04116 commented on test_email_validation.py
> +import unittest
"from unittest..." doesn't work. No matches in google(

2016-12-25 13:06 UTC, webknjaz requested changes

2016-12-25 13:06 UTC, webknjaz commented on .idea/email-validation.iml
> +<?xml version="1.0" encoding="UTF-8"?>
rm

2016-12-25 13:06 UTC, webknjaz commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
rm

2016-12-25 13:06 UTC, webknjaz commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
rm

2016-12-25 13:06 UTC, webknjaz commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
rm

2016-12-25 13:06 UTC, webknjaz commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
rm

2016-12-25 13:06 UTC, webknjaz commented on .travis.yml
> +- nosetests -s -v
Why did you remove running `pre-commit` utility?

2016-12-25 13:06 UTC, webknjaz commented on test_email_validation.py
> +from email_validation import validate_email
You need a module docstring at line 0.

2016-12-25 13:06 UTC, webknjaz commented on test_email_validation.py
> +        self.assertTrue(validate_email('123@123.com'))
Please add a docstring to this test method.

2016-12-25 13:15 UTC, m04116 commented on .idea/email-validation.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Have i remove above string?

2016-12-25 13:52 UTC, webknjaz approved these changes

2016-12-25 17:16 UTC, webknjaz commented
Make sure to refer the issue within your commit message. Like `Close #3`

2016-12-25 17:18 UTC, webknjaz requested changes
@m04116
1) re-title this PR to correspond its purpose
2) refer the issue you are solving

2016-12-26 21:06 UTC, webknjaz commented
Describe the purpose of this PR.

2016-12-26 22:31 UTC, webknjaz submitted a review, later dismissed

2016-12-27 18:52 UTC, m04116 commented
Python module with dummy function created. All tests are passed.

2016-12-27 19:37 UTC, webknjaz requested changes

2016-12-27 19:37 UTC, webknjaz commented on email_validation.py
> +"""Validate email module."""
Re-phrase this into `Email validation module.`

2016-12-27 19:37 UTC, webknjaz commented on email_validation.py
> +    """Email validation."""
`Validate email against pre-defined rules.`

2016-12-27 19:37 UTC, webknjaz commented on test_email_validation.py
> +    """Unit test for EmailValidation."""
test`s`

2016-12-27 19:37 UTC, webknjaz commented on test_email_validation.py
> +    """Unit test for EmailValidation."""
`for email validation module`

2016-12-27 19:37 UTC, webknjaz commented on test_email_validation.py
> +        """Test by assertTrue method."""
`Check whether validate_email function behaves correctly`

2016-12-28 14:14 UTC, webknjaz approved these changes

2016-12-28 20:45 UTC, merged